from __future__ import annotations

from .contracts import DepartmentWorkflow, OutputSpec, RequiredInput, Scenario


def _input(
    key: str,
    label: str,
    description: str = "",
    *,
    required: bool = True,
    examples: tuple[str, ...] = (),
) -> RequiredInput:
    return RequiredInput(
        key=key,
        label=label,
        description=description,
        required=required,
        examples=examples,
    )


def _output(
    key: str,
    label: str,
    description: str = "",
    *,
    format_hint: str = "",
) -> OutputSpec:
    return OutputSpec(
        key=key,
        label=label,
        description=description,
        format_hint=format_hint,
    )


DEFAULT_DEPARTMENT_WORKFLOWS: tuple[DepartmentWorkflow, ...] = (
    DepartmentWorkflow(
        department_id="client_dept",
        department_name="客户部",
        aliases=(
            "客户部",
            "客户",
            "中台客户部",
            "中台-客户",
            "中台客户",
            "市场部",
            "市场",
            "营销",
            "业务部",
            "商务市场",
            "marketing",
        ),
        functional_focus=(
            "需求入口",
            "客户关系",
            "客户触达",
            "客户邀约",
            "渠道转化",
            "活动复盘",
        ),
        training_focus=(
            "客户 brief",
            "客户触达话术",
            "节日营销方案",
            "渠道推广计划",
            "KPI 拆解",
        ),
        scenarios=(
            Scenario(
                scenario_id="customer_greeting",
                name="客户触达文案",
                description="面向客户或渠道伙伴生成可直接发送的触达话术。",
                keywords=(
                    "客户问候",
                    "客户问候话术",
                    "客户消息",
                    "vip",
                    "私域",
                    "客户触达",
                ),
                required_inputs=(
                    _input("audience", "目标客户", "客户类型、等级或行业。"),
                    _input("occasion", "触达场景", "节日、活动、回访或续约节点。"),
                    _input(
                        "offer",
                        "业务信息",
                        "权益、活动、产品或合作信息。",
                        required=False,
                    ),
                    _input("tone", "语气", "正式、亲切、活泼等。", required=False),
                ),
                expected_outputs=(
                    _output(
                        "message_draft",
                        "可发送话术",
                        format_hint="微信/私域/飞书短消息",
                    ),
                    _output("subject_options", "标题备选", format_hint="3-5 条"),
                    _output("followup_actions", "后续动作"),
                ),
                truth_requirements=(
                    "不得编造优惠、价格、客户身份或合作承诺。",
                    "客户部默认输出微信/私域/飞书触达话术；除非用户明确要求邮件，否则不得生成邮件主题或邮件正文。",
                ),
                material_requirements=(
                    "如涉及具体活动，需要提供活动时间、权益和适用客户范围。",
                ),
                test_task_directions=("端午 VIP 客户问候话术", "老客户续约回访话术"),
            ),
            Scenario(
                scenario_id="campaign_plan",
                name="营销活动方案",
                description="把目标、受众、渠道、节奏和指标组织成活动方案。",
                keywords=(
                    "营销计划",
                    "推广计划",
                    "营销方案",
                    "活动方案",
                    "渠道规划",
                    "campaign",
                ),
                required_inputs=(
                    _input("brand_or_product", "品牌/产品"),
                    _input("goal", "业务目标", examples=("拉新", "促活", "线索收集")),
                    _input("audience", "目标受众"),
                    _input("budget", "预算", required=False),
                    _input("timeline", "周期", required=False),
                ),
                expected_outputs=(
                    _output("strategy", "策略主线"),
                    _output("channels", "渠道打法"),
                    _output("timeline", "执行节奏"),
                    _output("kpis", "指标建议"),
                    _output("risks", "风险与前置条件"),
                ),
                truth_requirements=(
                    "预算、销量、投放效果只能基于用户提供材料或明确标注为假设。",
                ),
                material_requirements=(
                    "建议提供品牌资料、既往投放数据、预算区间和目标人群。",
                ),
                test_task_directions=("端午营销活动全案", "新品推广渠道规划"),
            ),
            Scenario(
                scenario_id="client_followup",
                name="客户回访/复联话术",
                description="面向老客户、沉默客户或犹豫客户生成可跟进、可审查的回访话术。",
                keywords=(
                    "客户回访",
                    "回访",
                    "复联",
                    "跟进客户",
                    "老客户",
                    "沉默客户",
                    "续约回访",
                    "客户复购",
                ),
                required_inputs=(
                    _input(
                        "client_segment",
                        "客户类型",
                        "老客户、VIP、沉默客户、犹豫客户或渠道伙伴。",
                        examples=("老客户", "VIP 客户", "沉默客户"),
                    ),
                    _input(
                        "last_interaction",
                        "上次互动",
                        "上次沟通时间、客户反馈或当前卡点。",
                        examples=("上次沟通", "客户反馈", "当前卡点"),
                    ),
                    _input(
                        "followup_goal",
                        "回访目标",
                        "确认意向、推进到店、收集反馈、促进复购或续约。",
                        examples=("确认意向", "推进到店", "促进复购", "续约"),
                    ),
                    _input(
                        "channel",
                        "触达渠道",
                        "微信、私域、社群、飞书或电话开场。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("opening_options", "开场白备选", format_hint="3 种语气"),
                    _output("message_draft", "可发送回访话术"),
                    _output("objection_replies", "异议回复"),
                    _output("followup_actions", "后续动作"),
                    _output("risk_notes", "风险提醒"),
                ),
                truth_requirements=(
                    "不得编造客户历史反馈、购买意向、到店承诺或续约承诺。",
                    "涉及优惠、权益、价格和库存必须来自用户材料或知识库来源。",
                    "默认按微信/私域/飞书触达话术输出，不默认生成邮件。",
                ),
                material_requirements=(
                    "至少需要客户类型、上次互动和回访目标。",
                    "如需承接具体权益，需要提供活动机制、适用范围和截止时间。",
                ),
                test_task_directions=("沉默客户复联话术", "老客户续约回访话术"),
            ),
            Scenario(
                scenario_id="event_invitation",
                name="客户活动邀约话术",
                description="为到店、沙龙、试驾、直播或社群活动生成邀约与提醒话术。",
                keywords=(
                    "活动邀约",
                    "客户邀约",
                    "邀约",
                    "邀请客户",
                    "到店邀约",
                    "试驾邀约",
                    "沙龙邀约",
                    "直播邀约",
                    "报名提醒",
                ),
                required_inputs=(
                    _input(
                        "event_name",
                        "活动名称",
                        "活动主题、项目名或场次。",
                        examples=("活动名称", "活动主题", "场次"),
                    ),
                    _input(
                        "event_time_place",
                        "时间地点",
                        "活动时间、地点、直播间或报名截止时间。",
                        examples=("时间地点", "报名截止", "直播间"),
                    ),
                    _input(
                        "audience",
                        "邀约对象",
                        "客户分层、名单范围或目标人群。",
                        examples=("邀约对象", "客户分层", "目标人群"),
                    ),
                    _input(
                        "invitation_goal",
                        "邀约目标",
                        "报名、到店、预约、转介绍或直播观看。",
                        examples=("报名", "到店", "预约", "转介绍"),
                    ),
                    _input(
                        "benefit",
                        "活动权益",
                        "到场礼、名额、权益或服务承诺。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("message_draft", "邀约话术"),
                    _output("reminder_copy", "提醒话术"),
                    _output("title_options", "标题/开头备选"),
                    _output("followup_actions", "跟进动作"),
                    _output("risk_notes", "风险提醒"),
                ),
                truth_requirements=(
                    "不得编造活动时间、地点、名额、权益、客户身份或到场承诺。",
                    "未提供权益时不得主动生成优惠、礼品或价格承诺。",
                    "默认按微信/私域/飞书触达话术输出，不默认生成邮件。",
                ),
                material_requirements=(
                    "至少需要活动名称、时间地点、邀约对象和邀约目标。",
                    "如涉及权益，需要提供权益内容、限制条件和有效期。",
                ),
                test_task_directions=("端午试驾活动客户邀约", "直播活动报名提醒"),
            ),
            Scenario(
                scenario_id="private_domain_campaign",
                name="私域活动转化话术",
                description="为社群、朋友圈、企微和私域运营生成分层触达与转化话术。",
                keywords=(
                    "私域活动",
                    "私域转化",
                    "社群活动",
                    "朋友圈",
                    "企微",
                    "微信群",
                    "群发",
                    "客户分层",
                    "转化话术",
                ),
                required_inputs=(
                    _input(
                        "audience_segment",
                        "人群分层",
                        "新客、老客、VIP、沉默客户或高意向客户。",
                        examples=("人群分层", "新客", "老客", "高意向客户"),
                    ),
                    _input(
                        "campaign_mechanism",
                        "活动机制",
                        "活动玩法、权益、参与条件或转化路径。",
                        examples=("活动机制", "参与条件", "转化路径"),
                    ),
                    _input(
                        "channel",
                        "私域渠道",
                        "朋友圈、微信群、企微私聊或飞书群。",
                        examples=("朋友圈", "微信群", "企微"),
                    ),
                    _input(
                        "conversion_goal",
                        "转化目标",
                        "报名、预约、复购、到店、领取资料或转介绍。",
                        examples=("报名", "预约", "复购", "到店"),
                    ),
                ),
                expected_outputs=(
                    _output("segment_strategy", "分层策略"),
                    _output("message_variants", "分层话术"),
                    _output("posting_sequence", "发布节奏"),
                    _output("image_prompt", "配图提示词", format_hint="可选"),
                    _output("review_checklist", "审查清单"),
                ),
                truth_requirements=(
                    "不得编造活动权益、价格、库存、客户数据或转化效果。",
                    "必须区分可确认事实和运营假设。",
                    "默认按微信/私域/飞书触达话术输出，不默认生成邮件。",
                ),
                material_requirements=(
                    "至少需要人群分层、活动机制、私域渠道和转化目标。",
                    "建议提供历史话术、素材链接、禁用词和活动规则。",
                ),
                test_task_directions=("私域活动转化话术", "朋友圈和社群分层话术"),
            ),
            Scenario(
                scenario_id="client_content_package",
                name="客户内容生产包",
                description="面向客户触达、邀约和私域转化生成文案、配图 brief 与视频脚本。",
                keywords=(
                    "客户邀约",
                    "客户触达",
                    "私域话术",
                    "客户文案",
                    "配图",
                    "生图",
                    "视频脚本",
                    "客户回访",
                    "活动邀约",
                ),
                required_inputs=(
                    _input("client_or_audience", "客户/受众", "客户类型、行业或人群。"),
                    _input(
                        "occasion", "触达场景", "邀约、回访、节日、活动或续约节点。"
                    ),
                    _input(
                        "brand_or_product",
                        "品牌/产品",
                        "涉及的品牌、车型、产品或服务。",
                    ),
                    _input(
                        "goal",
                        "业务目标",
                        examples=("邀约到店", "收集线索", "促进复购"),
                    ),
                    _input(
                        "offer",
                        "权益/活动信息",
                        "优惠、权益或活动机制。",
                        required=False,
                    ),
                    _input(
                        "channel",
                        "投放/发送渠道",
                        "飞书、微信、朋友圈、社群等。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output(
                        "message_draft",
                        "可发送文案",
                        format_hint="微信/私域/飞书短消息/社群话术",
                    ),
                    _output("subject_options", "标题备选", format_hint="3-5 条"),
                    _output(
                        "image_prompt",
                        "生图提示词",
                        format_hint="业务说明 + 模型 prompt",
                    ),
                    _output("video_script", "视频脚本", format_hint="镜头/旁白/字幕"),
                    _output("source_citations", "来源依据"),
                    _output("risk_notes", "风险提醒"),
                    _output("next_actions", "后续动作"),
                ),
                truth_requirements=(
                    "不得编造优惠、价格、客户身份、客户承诺或合作结果。",
                    "权益、活动机制和发送对象必须来自用户材料或知识库来源。",
                ),
                material_requirements=(
                    "至少需要客户/受众、触达场景、品牌/产品和业务目标。",
                    "如要输出生图/视频，需要提供或确认画面风格、平台和禁用元素。",
                ),
                test_task_directions=(
                    "客户邀约文案并配图",
                    "老客户回访话术加短视频脚本",
                ),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="brand_publicity",
        department_name="品宣部",
        aliases=("品宣部", "品宣", "品牌部", "宣发", "品牌宣传", "branding", "运营部"),
        functional_focus=(
            "直播运营",
            "账号内容运营",
            "媒介/KOC管理",
            "用户故事",
            "用户活动",
            "企微与社群",
            "舆情运营",
        ),
        training_focus=(
            "账号周/月复盘",
            "直播节奏与 KPI",
            "媒介/KOC任务闭环",
            "用户故事库",
            "社群舆情风险预警",
            "企微运营占位接口",
        ),
        scenarios=(
            Scenario(
                scenario_id="live_account_ops",
                name="直播/账号内容运营",
                description="整理直播、账号内容和起号动作，输出节奏、KPI 和复盘清单。",
                keywords=(
                    "直播运营",
                    "账号运营",
                    "内容运营",
                    "起号",
                    "爆品",
                    "引流品",
                    "直播复盘",
                    "月复盘",
                    "周复盘",
                    "KPI",
                ),
                required_inputs=(
                    _input(
                        "account_or_platform",
                        "账号/平台",
                        "抖音、视频号、小红书或直播间。",
                    ),
                    _input("period_or_goal", "周期/目标", "周、月、活动期或起号目标。"),
                    _input(
                        "current_data", "当前数据", "曝光、互动、线索、成交或直播指标。"
                    ),
                    _input(
                        "product_focus",
                        "主推内容",
                        "爆品、引流品、栏目或活动。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("ops_summary", "运营现状摘要"),
                    _output("content_calendar", "内容/直播节奏"),
                    _output("kpi_actions", "KPI 拆解动作"),
                    _output("review_findings", "复盘发现"),
                    _output("next_actions", "下一步"),
                ),
                truth_requirements=(
                    "不得编造账号数据、直播成交、平台规则或 KPI 完成情况。",
                    "没有数据时只能给方法和表格框架，不能写成已发生结果。",
                ),
                material_requirements=(
                    "需要提供账号/平台、周期目标和当前数据；没有数据时先补表头和采集口径。",
                ),
                test_task_directions=("直播账号运营周复盘", "起号内容节奏和 KPI 拆解"),
            ),
            Scenario(
                scenario_id="media_koc_management",
                name="媒介/KOC 管理",
                description="管理媒介、KOC 需求、任务下发、日报和反馈闭环。",
                keywords=(
                    "媒介",
                    "KOC",
                    "达人",
                    "任务下发",
                    "需求管理表",
                    "日报",
                    "反馈闭环",
                    "投放名单",
                    "内容回收",
                ),
                required_inputs=(
                    _input("campaign_or_project", "项目/活动"),
                    _input(
                        "media_scope", "媒介/KOC范围", "名单、平台、区域或合作类型。"
                    ),
                    _input(
                        "task_goal", "任务目标", "曝光、种草、报名、线索或素材回收。"
                    ),
                    _input("deadline", "截止时间", required=False),
                ),
                expected_outputs=(
                    _output("task_table", "任务下发表"),
                    _output("daily_report_fields", "日报字段"),
                    _output("feedback_loop", "反馈闭环"),
                    _output("risk_notes", "风险提醒"),
                ),
                truth_requirements=(
                    "不得编造达人名单、报价、投放效果或合作承诺。",
                    "外部合作口径、报价和排期必须来自用户材料或确认信息。",
                ),
                material_requirements=(
                    "建议提供媒介/KOC名单、任务目标、内容要求、截止时间和回收标准。",
                ),
                test_task_directions=(
                    "媒介KOC任务下发和日报复盘",
                    "达人内容回收反馈表",
                ),
            ),
            Scenario(
                scenario_id="user_story_campaign",
                name="用户故事/用户活动",
                description="沉淀用户故事库，整理沟通脚本、甲方审核、拍摄通告和成片审核。",
                keywords=(
                    "用户故事",
                    "用户故事库",
                    "用户活动",
                    "沟通脚本",
                    "甲方审核",
                    "拍摄通告",
                    "成片审核",
                    "用户证言",
                    "案例故事",
                ),
                required_inputs=(
                    _input(
                        "user_or_segment", "用户/人群", "用户标签、客户类型或故事对象。"
                    ),
                    _input(
                        "story_goal", "故事目标", "种草、信任背书、活动传播或复盘沉淀。"
                    ),
                    _input(
                        "known_facts", "已确认事实", "用户经历、车型、活动、拍摄信息。"
                    ),
                    _input(
                        "review_owner",
                        "审核方",
                        "甲方、项目负责人或内部审核人。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("story_outline", "故事框架"),
                    _output("communication_script", "用户沟通脚本"),
                    _output("shooting_notice", "拍摄/采集通告"),
                    _output("review_checklist", "审核清单"),
                    _output("risk_notes", "合规风险"),
                ),
                truth_requirements=(
                    "不得编造用户身份、真实经历、授权状态、拍摄结果或甲方审核意见。",
                    "用户证言和肖像授权必须来自确认材料。",
                ),
                material_requirements=(
                    "至少需要用户/人群、故事目标和已确认事实；涉及拍摄需补授权与审核人。",
                ),
                test_task_directions=(
                    "用户故事库沟通脚本和成片审核",
                    "用户活动案例故事采集",
                ),
            ),
            Scenario(
                scenario_id="community_public_opinion_ops",
                name="舆情/社群运营",
                description="处理社群维护、用户证言、风险预警、负面稀释和竞品负面抓取。",
                keywords=(
                    "舆情",
                    "社群",
                    "社群维护",
                    "风险预警",
                    "负面稀释",
                    "竞品负面",
                    "负面评论",
                    "用户证言",
                    "口碑",
                    "危机",
                ),
                required_inputs=(
                    _input(
                        "monitor_scope", "监测范围", "平台、社群、关键词或竞品对象。"
                    ),
                    _input("risk_signal", "风险信号", "评论、截图、关键词或用户反馈。"),
                    _input(
                        "desired_response",
                        "处理目标",
                        "预警、回应、稀释、复盘或社群维护。",
                    ),
                    _input("source_material", "来源材料", required=False),
                ),
                expected_outputs=(
                    _output("signal_summary", "信号摘要"),
                    _output("risk_level", "风险分级"),
                    _output("response_options", "回应/稀释动作"),
                    _output("community_actions", "社群维护动作"),
                    _output("escalation_notes", "升级提醒"),
                ),
                truth_requirements=(
                    "不得捏造舆情来源、截图内容、用户证言或竞品事实。",
                    "涉及实时舆情、平台评论或竞品信息时必须标注来源或说明需要检索。",
                ),
                material_requirements=(
                    "建议提供截图、链接、关键词、社群上下文和已确认处理口径。",
                ),
                test_task_directions=(
                    "社群舆情风险预警和负面稀释",
                    "竞品负面关键词日报",
                ),
            ),
            Scenario(
                scenario_id="wechat_private_domain_ops",
                name="企微/私域运营占位",
                description="先按内容库、触达、社群和复盘字段留接口；详细 SOP 待补充。",
                keywords=("企微运营", "企业微信", "企微", "私域内容库", "私域社群"),
                required_inputs=(
                    _input("audience_segment", "人群分层"),
                    _input("touchpoint_goal", "触达目标"),
                    _input("channel", "渠道", "企微私聊、社群、朋友圈或飞书。"),
                    _input("content_material", "内容素材", required=False),
                ),
                expected_outputs=(
                    _output("content_library_fields", "内容库字段"),
                    _output("touchpoint_sequence", "触达节奏"),
                    _output("review_fields", "复盘字段"),
                    _output("open_questions", "待补 SOP 问题"),
                ),
                truth_requirements=(
                    "企微运营 SOP 未补齐前，只输出可确认的结构和待确认项，不作效果承诺。",
                ),
                material_requirements=(
                    "需要补充人群分层、触达目标、渠道规则、素材来源和复盘口径。",
                ),
                test_task_directions=("企微内容库和触达复盘字段", "私域社群运营占位表"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="planning",
        department_name="策略部",
        aliases=(
            "策略部",
            "策略",
            "策划",
            "策划部",
            "中台策略部",
            "中台-策略",
            "中台策略",
            "中台策划",
            "战略",
            "规划",
            "strategy",
        ),
        functional_focus=(
            "创意",
            "方案框架",
            "文案方向",
            "竞品参考",
            "策略框架",
            "汇报结构",
        ),
        training_focus=(
            "创意发散",
            "海报思路",
            "视觉 brief",
            "行业趋势",
            "策略提案结构",
            "方案目录",
            "PPT页级小标题",
            "用户洞察",
            "竞品拆解",
        ),
        scenarios=(
            Scenario(
                scenario_id="proposal_framework_outline",
                name="方案框架/提案目录",
                description=(
                    "先搭标准化、层级清晰、逻辑闭环的策划框架；"
                    "再按目录和每页 PPT 小标题补充细化内容。"
                ),
                keywords=(
                    "方案框架",
                    "框架",
                    "目录",
                    "大纲",
                    "PPT",
                    "小标题",
                    "提案结构",
                    "方案结构",
                ),
                required_inputs=(
                    _input("project_or_topic", "项目/主题"),
                    _input("communication_goal", "目标", required=False),
                    _input("audience_or_client", "对象/客户", required=False),
                    _input("known_constraints", "已知限制", required=False),
                ),
                expected_outputs=(
                    _output(
                        "framework_toc",
                        "方案目录",
                        "先给可直接放进方案的目录结构。",
                        format_hint="按 1/2/3 层级输出，不跳层。",
                    ),
                    _output(
                        "slide_titles",
                        "PPT逐页小标题",
                        "每页一个小标题，体现递进逻辑。",
                        format_hint="P1/P2/P3...：页标题 + 本页作用。",
                    ),
                    _output(
                        "page_details",
                        "逐页补充细化",
                        "每页补 2-4 个要点，说明该页承接上页并推进到下一页。",
                    ),
                    _output(
                        "logic_loop",
                        "逻辑闭环检查",
                        "检查背景、洞察、策略、创意、执行、评估是否闭环。",
                    ),
                ),
                truth_requirements=(
                    "没有用户材料时只能输出框架与假设，不能编造真实数据。",
                ),
                material_requirements=(
                    "建议提供客户/项目背景、目标、受众、预算、渠道和历史方案；缺失时先给可改框架。",
                ),
                test_task_directions=("活动方案框架目录", "提案PPT逐页小标题"),
            ),
            Scenario(
                scenario_id="project_progress_framework",
                name="项目进度汇报框架",
                description="把项目现状整理成适合汇报的进度、风险和下一步。",
                keywords=(
                    "项目进度",
                    "跟进框架",
                    "进度汇报",
                    "项目跟进",
                    "周报",
                    "复盘",
                ),
                required_inputs=(
                    _input("project_name", "项目名称"),
                    _input("current_status", "当前状态"),
                    _input("milestones", "关键节点", required=False),
                    _input("blockers", "风险/阻塞", required=False),
                ),
                expected_outputs=(
                    _output("progress", "进度摘要"),
                    _output("risks", "风险判断"),
                    _output("decisions_needed", "待决策事项"),
                    _output("next_actions", "下一步动作"),
                ),
                truth_requirements=("项目进度、负责人和时间节点必须来自用户材料。",),
                material_requirements=(
                    "建议提供项目背景、当前进展、历史纪要或任务清单。",
                ),
                test_task_directions=("本周项目进度跟进框架", "项目复盘汇报结构"),
            ),
            Scenario(
                scenario_id="insight_brief",
                name="洞察/竞品简报",
                description="围绕问题拆出洞察、证据、机会点和行动建议。",
                keywords=("洞察", "竞品", "拆解", "分析", "策略", "机会点", "人群"),
                required_inputs=(
                    _input("question", "核心问题"),
                    _input("market_or_competitor", "市场/竞品对象", required=False),
                    _input("evidence", "已有材料", required=False),
                ),
                expected_outputs=(
                    _output("key_findings", "关键发现"),
                    _output("evidence_map", "证据链"),
                    _output("opportunities", "机会点"),
                    _output("recommendations", "建议动作"),
                ),
                truth_requirements=("没有证据时需要明确写出假设，不得伪造数据来源。",),
                material_requirements=(
                    "建议提供竞品链接、用户反馈、销售数据或调研摘要。",
                ),
                test_task_directions=("竞品活动拆解", "目标人群洞察框架"),
            ),
            Scenario(
                scenario_id="short_video_visual_brief",
                name="短视频脚本与生图 Brief",
                description="把策划任务拆成创意 brief、短视频脚本、分镜和生图 prompt。",
                keywords=(
                    "短视频脚本",
                    "视频脚本",
                    "分镜",
                    "生图",
                    "图片 prompt",
                    "视觉 brief",
                    "旁白",
                    "镜头",
                    "内容包",
                ),
                required_inputs=(
                    _input("project_or_brand", "项目/品牌", "项目、客户、品牌或车型。"),
                    _input(
                        "communication_goal",
                        "传播目标",
                        examples=("拉新", "种草", "活动预热"),
                    ),
                    _input("audience", "目标人群"),
                    _input(
                        "platform", "发布平台", examples=("抖音", "视频号", "小红书")
                    ),
                    _input(
                        "source_material",
                        "已有资料",
                        "历史方案、卖点、附件或知识库来源。",
                        required=False,
                    ),
                    _input(
                        "style_constraints",
                        "风格/禁用元素",
                        "画面风格、品牌口径、禁用词。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("creative_brief", "创意 Brief"),
                    _output("key_insight", "核心洞察"),
                    _output("video_script", "视频脚本"),
                    _output("storyboard", "分镜表"),
                    _output("voiceover", "旁白/字幕"),
                    _output("image_prompt", "生图提示词"),
                    _output("source_citations", "来源依据"),
                    _output("review_checklist", "审查清单"),
                ),
                truth_requirements=(
                    "必须区分资料事实与创意假设。",
                    "不得伪造客户、车型、卖点、数据或历史项目结论。",
                ),
                material_requirements=(
                    "建议提供历史方案、目标人群、平台、传播目标和品牌口径。",
                    "没有来源时必须先输出补资料请求，不进入深度生成。",
                ),
                test_task_directions=(
                    "做一个短视频脚本和生图 prompt",
                    "策划一个视频分镜内容包",
                ),
            ),
            Scenario(
                scenario_id="video_storyboard_production",
                name="短视频分镜生产",
                description="把策划 brief 拆成可拍摄的分镜、镜头调度、旁白字幕和素材清单。",
                keywords=(
                    "短视频分镜",
                    "视频分镜",
                    "分镜脚本",
                    "镜头脚本",
                    "拍摄脚本",
                    "镜头表",
                    "转场",
                    "旁白字幕",
                    "拍摄清单",
                ),
                required_inputs=(
                    _input(
                        "project_or_brand",
                        "项目/品牌",
                        "项目、客户、品牌、车型或活动。",
                        examples=("项目/品牌", "品牌", "车型", "活动"),
                    ),
                    _input(
                        "video_goal",
                        "视频目标",
                        "种草、预热、转化、招商、复盘或品牌传播。",
                        examples=("视频目标", "种草", "预热", "转化"),
                    ),
                    _input(
                        "audience",
                        "目标人群",
                        "目标客户、受众画像或渠道人群。",
                        examples=("目标人群", "受众", "客户画像"),
                    ),
                    _input(
                        "duration_platform",
                        "时长/平台",
                        "视频时长、发布平台和画幅。",
                        examples=("时长", "平台", "画幅", "抖音", "视频号"),
                    ),
                    _input(
                        "source_material",
                        "已有资料",
                        "产品卖点、活动机制、历史方案或附件。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("creative_brief", "创意 Brief"),
                    _output(
                        "storyboard", "分镜表", format_hint="镜号/画面/镜头/字幕/旁白"
                    ),
                    _output("shot_list", "拍摄清单"),
                    _output("voiceover", "旁白/字幕"),
                    _output("editing_notes", "剪辑与转场建议"),
                    _output("review_checklist", "审查清单"),
                ),
                truth_requirements=(
                    "产品卖点、活动机制、客户信息和历史项目结论必须来自资料。",
                    "创意画面和镜头建议必须标注为创意假设，不得伪装成事实。",
                    "涉及品牌视觉、人物肖像、门店和车辆素材时必须列审查项。",
                ),
                material_requirements=(
                    "至少需要项目/品牌、视频目标、目标人群和时长/平台。",
                    "建议提供品牌口径、素材清单、禁用元素和历史方案。",
                ),
                test_task_directions=("短视频分镜脚本", "视频号拍摄镜头表"),
            ),
            Scenario(
                scenario_id="brand_review_check",
                name="品牌审查/合规检查",
                description="审查内容方案、文案、分镜或媒体 prompt 是否符合品牌口径和事实边界。",
                keywords=(
                    "品牌审查",
                    "品牌检查",
                    "合规审查",
                    "口径检查",
                    "禁用词",
                    "风险审查",
                    "传播审查",
                    "素材审查",
                    "prompt 审查",
                ),
                required_inputs=(
                    _input(
                        "review_material",
                        "待审材料",
                        "文案、分镜、prompt、海报稿、视频脚本或附件。",
                        examples=("待审材料", "文案", "分镜", "prompt", "附件"),
                    ),
                    _input(
                        "brand_guideline",
                        "品牌口径",
                        "品牌规范、项目口径、禁用词或审查标准。",
                        examples=("品牌口径", "品牌规范", "禁用词", "审查标准"),
                    ),
                    _input(
                        "usage_context",
                        "使用场景",
                        "发布平台、受众、活动场景或客户场景。",
                        examples=("使用场景", "发布平台", "受众", "活动场景"),
                    ),
                ),
                expected_outputs=(
                    _output("risk_summary", "风险摘要"),
                    _output("fact_check_items", "事实核查项"),
                    _output("brand_consistency_notes", "品牌一致性意见"),
                    _output("revision_suggestions", "修改建议"),
                    _output("approval_checklist", "确认清单"),
                ),
                truth_requirements=(
                    "不得把未提供的品牌规范、法务要求或客户承诺当作事实。",
                    "必须区分确定违规、疑似风险和需要人工确认的项目。",
                    "没有品牌口径或待审材料时必须先补资料，不得直接给通过结论。",
                ),
                material_requirements=(
                    "至少需要待审材料、品牌口径和使用场景。",
                    "建议提供历史通过案例、禁用词表、平台规则和法务要求。",
                ),
                test_task_directions=("品牌审查和禁用词检查", "视频脚本口径检查"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="executive_office",
        department_name="总经办",
        aliases=("总经办", "办公室", "总办", "行政办", "总经理办公室"),
        functional_focus=("会议纪要", "决策跟进", "制度通知", "跨部门协调"),
        training_focus=("正式纪要", "决策事项追踪", "通知公告", "老板视角摘要"),
        scenarios=(
            Scenario(
                scenario_id="meeting_minutes",
                name="会议纪要整理",
                description="把会议讨论整理为正式纪要、决策和待办。",
                keywords=(
                    "会议纪要",
                    "会议要点",
                    "正式纪要",
                    "会议整理",
                    "决议",
                    "纪要",
                ),
                required_inputs=(
                    _input("meeting_topic", "会议主题"),
                    _input("raw_notes", "原始记录"),
                    _input("attendees", "参会人", required=False),
                ),
                expected_outputs=(
                    _output("summary", "会议摘要"),
                    _output("decisions", "决策事项"),
                    _output("action_items", "行动项"),
                    _output("open_questions", "遗留问题"),
                ),
                truth_requirements=(
                    "不得新增会议中未出现的决策、人员承诺或截止时间。",
                ),
                material_requirements=(
                    "建议提供聊天记录、录音转写、参会人和会议背景。",
                ),
                test_task_directions=("昨天会议要点正式纪要", "老板会议决策追踪表"),
            ),
            Scenario(
                scenario_id="announcement_notice",
                name="通知/公告起草",
                description="生成正式、清晰、低歧义的内部通知。",
                keywords=("通知", "公告", "制度", "安排", "发文", "内部信"),
                required_inputs=(
                    _input("topic", "通知主题"),
                    _input("audience", "通知对象"),
                    _input("policy_or_action", "要求/安排"),
                    _input("deadline", "时间要求", required=False),
                ),
                expected_outputs=(
                    _output("notice_draft", "通知正文"),
                    _output("key_points", "要点清单"),
                    _output("faq", "可能追问", format_hint="可选"),
                ),
                truth_requirements=("涉及制度、奖惩和人事安排必须以原文材料为准。",),
                material_requirements=(
                    "建议提供制度依据、执行范围、发布时间和联系人。",
                ),
                test_task_directions=("内部活动通知", "制度调整公告草稿"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="execution_ops",
        department_name="活动统筹部",
        aliases=(
            "活动统筹部",
            "活动统筹",
            "执行部门",
            "执行部",
            "执行运营",
            "执行",
            "项目执行",
            "活动执行",
            "运营部",
            "operations",
        ),
        functional_focus=(
            "任务拆解",
            "排期推进",
            "落地沟通",
            "现场执行",
            "物料验收",
            "礼品生产",
            "风险闭环",
        ),
        training_focus=(
            "执行分工表",
            "活动点检",
            "物料安装",
            "验收材料",
            "礼品打样",
            "库存管理",
            "时间节点",
            "负责人拆分",
            "风险预案",
        ),
        scenarios=(
            Scenario(
                scenario_id="execution_plan",
                name="执行排期拆解",
                description="把活动或项目拆成可执行步骤、负责人和时间节点。",
                keywords=(
                    "拆解",
                    "执行步骤",
                    "时间节点",
                    "排期",
                    "执行计划",
                    "执行分工表",
                    "项目启动会",
                    "落地沟通会",
                    "落地",
                ),
                required_inputs=(
                    _input("project_or_event", "项目/活动"),
                    _input("deadline", "最终时间"),
                    _input("owners", "参与角色", required=False),
                    _input("constraints", "限制条件", required=False),
                ),
                expected_outputs=(
                    _output("work_breakdown", "任务拆解"),
                    _output("timeline", "时间排期"),
                    _output("owner_matrix", "负责人矩阵"),
                    _output("risk_controls", "风险预案"),
                ),
                truth_requirements=(
                    "负责人、场地、预算和截止时间不明确时需要标注待确认。",
                ),
                material_requirements=(
                    "建议提供活动 brief、项目执行分工表、硬截止时间和交付物清单。",
                ),
                test_task_directions=("端午营销活动执行步骤", "线下活动排期与风险表"),
            ),
            Scenario(
                scenario_id="venue_material_acceptance",
                name="场地/物料安装验收",
                description="把场地、物料、安装和点检事项整理成落地检查与验收闭环。",
                keywords=(
                    "场地",
                    "勘场",
                    "场地规划图",
                    "物料",
                    "物料明细",
                    "安装",
                    "点检",
                    "拍照验收",
                    "验收材料",
                    "财务系统验收",
                    "安全宣导",
                ),
                required_inputs=(
                    _input("project_or_event", "项目/活动"),
                    _input("venue_or_layout", "场地/规划图", required=False),
                    _input("material_list", "物料清单", required=False),
                    _input("installation_time", "安装/进场时间", required=False),
                    _input("acceptance_standard", "验收标准", required=False),
                ),
                expected_outputs=(
                    _output("site_checklist", "场地点检清单"),
                    _output("material_installation_plan", "物料安装计划"),
                    _output("acceptance_photo_list", "拍照验收清单"),
                    _output("safety_risks", "安全与合规风险"),
                    _output("handoff_notes", "交接与待确认项"),
                ),
                truth_requirements=(
                    "场地、尺寸、物料数量、安装时间和验收结论必须来自用户材料或现场确认。",
                    "不得替代财务系统、甲方或项目负责人作最终验收结论。",
                ),
                material_requirements=(
                    "建议提供场地规划图、物料明细表、最终定稿设计、安装时间和验收标准。",
                ),
                test_task_directions=("场地物料安装验收清单", "活动点检和验收材料"),
            ),
            Scenario(
                scenario_id="gift_production_inventory",
                name="礼品打样/生产/库存",
                description="跟踪礼品设计打样、工厂生产、抽检、交付和出入库。",
                keywords=(
                    "礼品",
                    "打样",
                    "生产",
                    "大货",
                    "模具",
                    "抽检",
                    "入库",
                    "出库",
                    "库存",
                    "库存表",
                    "生产工厂",
                ),
                required_inputs=(
                    _input("gift_item", "礼品/产品"),
                    _input("quantity", "生产数量", required=False),
                    _input("delivery_deadline", "交付时间", required=False),
                    _input("quality_standard", "交付/验收标准", required=False),
                    _input("contract_terms", "合同/付款信息", required=False),
                ),
                expected_outputs=(
                    _output("sample_tracking", "打样跟踪表"),
                    _output("production_schedule", "生产排期"),
                    _output("quality_checklist", "抽检与验收清单"),
                    _output("inventory_handoff", "出入库交接"),
                    _output("escalation_plan", "延期/不合格处理预案"),
                ),
                truth_requirements=(
                    "生产数量、合同价格、付款、回款、发票和库存损失责任必须来自确认材料。",
                    "不合格、延期、退款或追责建议只能作为预案，不能直接作事实结论。",
                ),
                material_requirements=(
                    "建议提供生产数量、交付时间、交付标准、合同价格、付款节点、供应商和库存表。",
                ),
                test_task_directions=("礼品打样生产跟踪", "礼品库存出入库清单"),
            ),
            Scenario(
                scenario_id="task_checklist",
                name="待办检查清单",
                description="把模糊任务转成检查清单和验收标准。",
                keywords=("待办", "清单", "检查表", "验收", "验收材料", "SOP", "流程"),
                required_inputs=(
                    _input("task_goal", "任务目标"),
                    _input("deliverables", "交付物", required=False),
                    _input("quality_bar", "验收标准", required=False),
                ),
                expected_outputs=(
                    _output("checklist", "检查清单"),
                    _output("acceptance_criteria", "验收标准"),
                    _output("handoff_notes", "交接说明"),
                ),
                truth_requirements=("验收标准不明确时应给出待确认字段。",),
                material_requirements=("建议提供历史 SOP、客户要求或交付模板。",),
                test_task_directions=("活动执行检查清单", "项目交接 SOP"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="design_dept",
        department_name="设计部",
        aliases=("设计部", "设计", "主设", "平面设计", "视觉设计", "designer"),
        functional_focus=("设计落地", "视觉检查", "制作文件", "源文件入库"),
        training_focus=("VI检查", "尺寸比例", "字体色调", "设计交付", "制作文件规范"),
        scenarios=(
            Scenario(
                scenario_id="design_delivery_review",
                name="设计稿交付检查",
                description="检查设计稿是否满足创意、品牌、制作和交付要求。",
                keywords=(
                    "设计稿",
                    "VI",
                    "色调",
                    "字体",
                    "背景",
                    "尺寸比例",
                    "视觉检查",
                    "设计交付",
                    "制作文件",
                    "源文件",
                    "排版",
                ),
                required_inputs=(
                    _input("design_material", "设计稿/说明"),
                    _input("brand_or_project", "品牌/项目", required=False),
                    _input("usage_context", "使用场景", required=False),
                    _input("production_specs", "制作规格", required=False),
                ),
                expected_outputs=(
                    _output("visual_review", "视觉检查意见"),
                    _output("production_risks", "制作风险"),
                    _output("revision_checklist", "修改清单"),
                    _output("handoff_files", "交付文件清单"),
                ),
                truth_requirements=(
                    "品牌规范、尺寸、物料工艺和最终通过结论必须来自用户材料或负责人确认。",
                ),
                material_requirements=(
                    "建议提供设计稿、品牌口径、尺寸比例、使用场景和制作工艺要求。",
                ),
                test_task_directions=("设计稿VI和尺寸检查", "制作文件交付清单"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="film_production",
        department_name="影视制作部",
        aliases=("影视制作部", "影视", "影视制作", "编导", "拍摄", "后期", "剪辑"),
        functional_focus=("拍摄通告", "现场拍摄", "后期剪辑", "成片交付"),
        training_focus=("机位规划", "道化服准备", "拍摄重点", "验收材料", "成片交付"),
        scenarios=(
            Scenario(
                scenario_id="video_shooting_delivery",
                name="视频拍摄/交付执行",
                description="把已确认的视频需求落成拍摄通告、机位安排、现场跟拍和成片交付清单。",
                keywords=(
                    "拍摄通告",
                    "机位",
                    "道化服",
                    "现场拍摄",
                    "跟拍",
                    "后期剪辑",
                    "成片",
                    "成片交付",
                    "拍摄重点",
                    "验收材料",
                ),
                required_inputs=(
                    _input("project_or_video", "项目/视频"),
                    _input("shooting_goal", "拍摄目标", required=False),
                    _input("schedule_location", "时间/地点", required=False),
                    _input("shot_requirements", "镜头/机位要求", required=False),
                    _input("delivery_standard", "交付标准", required=False),
                ),
                expected_outputs=(
                    _output("shooting_notice", "拍摄通告"),
                    _output("camera_plan", "机位与人员安排"),
                    _output("shooting_checklist", "现场拍摄清单"),
                    _output("post_production_plan", "后期交付计划"),
                    _output("acceptance_materials", "验收材料清单"),
                ),
                truth_requirements=(
                    "拍摄时间、地点、人员、机位数量和交付标准必须来自确认材料。",
                    "不得替代市场、甲方或项目负责人作最终验收结论。",
                ),
                material_requirements=(
                    "建议提供需求 brief、分镜、拍摄时间地点、人员安排、交付标准和品牌口径。",
                ),
                test_task_directions=("拍摄通告和机位表", "成片交付验收材料"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="ai_application",
        department_name="AI应用部",
        aliases=(
            "AI应用部",
            "AI应用",
            "ai应用部",
            "数字化应用部",
            "数字化应用",
            "小助手配置",
            "机器人配置",
        ),
        functional_focus=("AI工具落地", "自动化流程", "知识库接入", "小助手配置"),
        training_focus=(
            "工具选型",
            "工作流梳理",
            "机器人配置",
            "权限与数据边界",
            "使用培训",
        ),
        scenarios=(
            Scenario(
                scenario_id="ai_workflow_enablement",
                name="AI应用/自动化落地",
                description="把部门使用场景整理成 AI 工具配置、自动化流程、知识库接入和培训清单。",
                keywords=(
                    "AI应用",
                    "AI工具",
                    "自动化",
                    "工作流",
                    "知识库接入",
                    "机器人配置",
                    "小助手配置",
                    "部门小助手",
                    "工具选型",
                    "使用培训",
                    "权限",
                ),
                required_inputs=(
                    _input("department_or_team", "部门/团队"),
                    _input("business_scenario", "业务场景"),
                    _input("current_materials", "现有资料/系统", required=False),
                    _input("constraints", "权限/数据限制", required=False),
                ),
                expected_outputs=(
                    _output("workflow_map", "工作流梳理"),
                    _output("tooling_plan", "AI工具/配置方案"),
                    _output("data_boundary", "数据与权限边界"),
                    _output("rollout_checklist", "上线检查清单"),
                    _output("training_notes", "培训要点"),
                ),
                truth_requirements=(
                    "权限、账号、客户资料、内部数据和系统能力必须以现有配置或确认材料为准。",
                    "不得承诺未验证的自动化能力、第三方接口能力或数据访问权限。",
                ),
                material_requirements=(
                    "建议提供部门场景、现有文件位置、系统限制、权限范围和期望输出样例。",
                ),
                test_task_directions=("AI应用工作流配置", "部门小助手知识库接入方案"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="general_affairs",
        department_name="综合部",
        aliases=("综合部", "综合", "行政", "行政综合", "办公室综合"),
        functional_focus=("行政通知", "内部协调", "资料归档", "服务答疑"),
        training_focus=("通知整理", "跨部门事项", "归档规范", "标准回复"),
        scenarios=(
            Scenario(
                scenario_id="admin_notice",
                name="行政通知/制度说明",
                description="把行政安排或内部规则整理为清晰通知、执行要点和 FAQ。",
                keywords=(
                    "行政通知",
                    "办公规则",
                    "制度说明",
                    "内部通知",
                    "领用",
                    "行政",
                ),
                required_inputs=(
                    _input("policy_or_arrangement", "制度/安排原文"),
                    _input("audience", "适用对象"),
                    _input("effective_time", "执行时间", required=False),
                    _input("contact", "联系人", required=False),
                ),
                expected_outputs=(
                    _output("notice_draft", "通知正文"),
                    _output("key_points", "执行要点"),
                    _output("faq", "常见问题"),
                    _output("open_questions", "待确认项"),
                ),
                truth_requirements=(
                    "制度条款、适用范围和执行时间必须来自用户提供材料。",
                ),
                material_requirements=(
                    "建议提供制度原文、适用范围、执行时间和联系人。",
                ),
                test_task_directions=("办公用品领用规则通知", "内部流程调整说明"),
            ),
            Scenario(
                scenario_id="coordination_digest",
                name="跨部门协调清单",
                description="把多方反馈整理为待办、负责人、截止时间和风险。",
                keywords=("跨部门", "协调", "反馈汇总", "待办", "负责人", "行政协调"),
                required_inputs=(
                    _input("coordination_topic", "协调事项"),
                    _input("raw_feedback", "各方反馈"),
                    _input("deadline", "截止时间", required=False),
                    _input("participants", "参与部门/人员", required=False),
                ),
                expected_outputs=(
                    _output("summary", "反馈摘要"),
                    _output("action_items", "待办清单"),
                    _output("owner_matrix", "负责人矩阵"),
                    _output("risks", "风险与待确认项"),
                ),
                truth_requirements=("不得新增未被确认的负责人、承诺或截止时间。",),
                material_requirements=(
                    "建议提供聊天记录、表单反馈、参与人员和目标时间。",
                ),
                test_task_directions=("团建安排反馈汇总", "跨部门事项推进表"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="finance",
        department_name="财务部",
        aliases=("财务", "财务部", "会计", "出纳", "财务管理"),
        functional_focus=("报销审核", "发票检查", "预算汇总", "费用分析"),
        training_focus=("报销材料检查", "发票缺项提醒", "费用分类", "预算执行汇总"),
        scenarios=(
            Scenario(
                scenario_id="reimbursement_invoice_check",
                name="报销/发票材料检查",
                description="把报销说明、票据信息和附件整理为缺项清单与复核提醒。",
                keywords=("报销", "发票", "票据", "付款", "附件", "缺项", "财务审核"),
                required_inputs=(
                    _input("expense_context", "费用事项", "报销或付款对应的业务事项。"),
                    _input(
                        "invoice_info",
                        "发票/票据信息",
                        "发票内容、金额、税号或附件摘要。",
                    ),
                    _input(
                        "policy_basis",
                        "制度依据",
                        "对应报销制度或审批要求。",
                        required=False,
                    ),
                    _input("approver", "审批人/部门", required=False),
                ),
                expected_outputs=(
                    _output("material_checklist", "材料检查清单"),
                    _output("missing_items", "缺失/待补充项"),
                    _output("risk_flags", "复核风险提示"),
                    _output("next_actions", "下一步处理建议"),
                ),
                truth_requirements=(
                    "金额、发票真伪、付款对象和审批结论必须由财务人员基于原始凭证确认。",
                ),
                material_requirements=(
                    "建议提供发票截图、报销说明、合同/订单、付款申请和公司制度依据。",
                ),
                test_task_directions=("报销发票材料检查清单", "付款申请缺项提醒"),
            ),
            Scenario(
                scenario_id="budget_cost_summary",
                name="预算/费用汇总",
                description="把费用明细整理为分类汇总、异常项和待确认问题。",
                keywords=("预算", "费用", "成本", "支出", "汇总", "对账", "预算执行"),
                required_inputs=(
                    _input("period", "统计周期"),
                    _input("expense_items", "费用明细"),
                    _input("budget_baseline", "预算口径", required=False),
                    _input("category_rules", "分类规则", required=False),
                ),
                expected_outputs=(
                    _output("cost_summary", "费用分类汇总"),
                    _output("variance_notes", "预算差异说明"),
                    _output("exceptions", "异常/待确认项"),
                    _output("report_draft", "汇报口径草稿"),
                ),
                truth_requirements=(
                    "费用数字必须来自用户提供明细，不得自行补数或替代财务核算。",
                ),
                material_requirements=(
                    "建议提供费用明细表、预算口径、科目分类规则和历史对账记录。",
                ),
                test_task_directions=("月度费用分类汇总", "项目预算执行差异说明"),
            ),
        ),
    ),
)
