from __future__ import annotations

from .contracts import DepartmentWorkflow, OutputSpec, RequiredInput, Scenario


def _input(
    key: str,
    label: str,
    description: str = "",
    *,
    required: bool = True,
    examples: tuple[str, ...] = (),
) -> RequiredInput:
    return RequiredInput(
        key=key,
        label=label,
        description=description,
        required=required,
        examples=examples,
    )


def _output(
    key: str,
    label: str,
    description: str = "",
    *,
    format_hint: str = "",
) -> OutputSpec:
    return OutputSpec(
        key=key,
        label=label,
        description=description,
        format_hint=format_hint,
    )


DEFAULT_DEPARTMENT_WORKFLOWS: tuple[DepartmentWorkflow, ...] = (
    DepartmentWorkflow(
        department_id="client_dept",
        department_name="客户部",
        aliases=(
            "客户部",
            "客户",
            "市场部",
            "市场",
            "营销",
            "业务部",
            "商务市场",
            "marketing",
        ),
        functional_focus=("客户触达", "客户邀约", "渠道转化", "活动复盘"),
        training_focus=("客户触达话术", "节日营销方案", "渠道推广计划", "KPI 拆解"),
        scenarios=(
            Scenario(
                scenario_id="customer_greeting",
                name="客户触达文案",
                description="面向客户或渠道伙伴生成可直接发送的触达话术。",
                keywords=(
                    "客户问候",
                    "客户问候话术",
                    "客户消息",
                    "vip",
                    "私域",
                    "客户触达",
                ),
                required_inputs=(
                    _input("audience", "目标客户", "客户类型、等级或行业。"),
                    _input("occasion", "触达场景", "节日、活动、回访或续约节点。"),
                    _input(
                        "offer",
                        "业务信息",
                        "权益、活动、产品或合作信息。",
                        required=False,
                    ),
                    _input("tone", "语气", "正式、亲切、活泼等。", required=False),
                ),
                expected_outputs=(
                    _output(
                        "message_draft",
                        "可发送话术",
                        format_hint="微信/私域/飞书短消息",
                    ),
                    _output("subject_options", "标题备选", format_hint="3-5 条"),
                    _output("followup_actions", "后续动作"),
                ),
                truth_requirements=(
                    "不得编造优惠、价格、客户身份或合作承诺。",
                    "客户部默认输出微信/私域/飞书触达话术；除非用户明确要求邮件，否则不得生成邮件主题或邮件正文。",
                ),
                material_requirements=(
                    "如涉及具体活动，需要提供活动时间、权益和适用客户范围。",
                ),
                test_task_directions=("端午 VIP 客户问候话术", "老客户续约回访话术"),
            ),
            Scenario(
                scenario_id="campaign_plan",
                name="营销活动方案",
                description="把目标、受众、渠道、节奏和指标组织成活动方案。",
                keywords=(
                    "营销计划",
                    "推广计划",
                    "营销方案",
                    "活动方案",
                    "渠道规划",
                    "campaign",
                ),
                required_inputs=(
                    _input("brand_or_product", "品牌/产品"),
                    _input("goal", "业务目标", examples=("拉新", "促活", "线索收集")),
                    _input("audience", "目标受众"),
                    _input("budget", "预算", required=False),
                    _input("timeline", "周期", required=False),
                ),
                expected_outputs=(
                    _output("strategy", "策略主线"),
                    _output("channels", "渠道打法"),
                    _output("timeline", "执行节奏"),
                    _output("kpis", "指标建议"),
                    _output("risks", "风险与前置条件"),
                ),
                truth_requirements=(
                    "预算、销量、投放效果只能基于用户提供材料或明确标注为假设。",
                ),
                material_requirements=(
                    "建议提供品牌资料、既往投放数据、预算区间和目标人群。",
                ),
                test_task_directions=("端午营销活动全案", "新品推广渠道规划"),
            ),
            Scenario(
                scenario_id="client_followup",
                name="客户回访/复联话术",
                description="面向老客户、沉默客户或犹豫客户生成可跟进、可审查的回访话术。",
                keywords=(
                    "客户回访",
                    "回访",
                    "复联",
                    "跟进客户",
                    "老客户",
                    "沉默客户",
                    "续约回访",
                    "客户复购",
                ),
                required_inputs=(
                    _input(
                        "client_segment",
                        "客户类型",
                        "老客户、VIP、沉默客户、犹豫客户或渠道伙伴。",
                        examples=("老客户", "VIP 客户", "沉默客户"),
                    ),
                    _input(
                        "last_interaction",
                        "上次互动",
                        "上次沟通时间、客户反馈或当前卡点。",
                        examples=("上次沟通", "客户反馈", "当前卡点"),
                    ),
                    _input(
                        "followup_goal",
                        "回访目标",
                        "确认意向、推进到店、收集反馈、促进复购或续约。",
                        examples=("确认意向", "推进到店", "促进复购", "续约"),
                    ),
                    _input(
                        "channel",
                        "触达渠道",
                        "微信、私域、社群、飞书或电话开场。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("opening_options", "开场白备选", format_hint="3 种语气"),
                    _output("message_draft", "可发送回访话术"),
                    _output("objection_replies", "异议回复"),
                    _output("followup_actions", "后续动作"),
                    _output("risk_notes", "风险提醒"),
                ),
                truth_requirements=(
                    "不得编造客户历史反馈、购买意向、到店承诺或续约承诺。",
                    "涉及优惠、权益、价格和库存必须来自用户材料或知识库来源。",
                    "默认按微信/私域/飞书触达话术输出，不默认生成邮件。",
                ),
                material_requirements=(
                    "至少需要客户类型、上次互动和回访目标。",
                    "如需承接具体权益，需要提供活动机制、适用范围和截止时间。",
                ),
                test_task_directions=("沉默客户复联话术", "老客户续约回访话术"),
            ),
            Scenario(
                scenario_id="event_invitation",
                name="客户活动邀约话术",
                description="为到店、沙龙、试驾、直播或社群活动生成邀约与提醒话术。",
                keywords=(
                    "活动邀约",
                    "客户邀约",
                    "邀约",
                    "邀请客户",
                    "到店邀约",
                    "试驾邀约",
                    "沙龙邀约",
                    "直播邀约",
                    "报名提醒",
                ),
                required_inputs=(
                    _input(
                        "event_name",
                        "活动名称",
                        "活动主题、项目名或场次。",
                        examples=("活动名称", "活动主题", "场次"),
                    ),
                    _input(
                        "event_time_place",
                        "时间地点",
                        "活动时间、地点、直播间或报名截止时间。",
                        examples=("时间地点", "报名截止", "直播间"),
                    ),
                    _input(
                        "audience",
                        "邀约对象",
                        "客户分层、名单范围或目标人群。",
                        examples=("邀约对象", "客户分层", "目标人群"),
                    ),
                    _input(
                        "invitation_goal",
                        "邀约目标",
                        "报名、到店、预约、转介绍或直播观看。",
                        examples=("报名", "到店", "预约", "转介绍"),
                    ),
                    _input(
                        "benefit",
                        "活动权益",
                        "到场礼、名额、权益或服务承诺。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("message_draft", "邀约话术"),
                    _output("reminder_copy", "提醒话术"),
                    _output("title_options", "标题/开头备选"),
                    _output("followup_actions", "跟进动作"),
                    _output("risk_notes", "风险提醒"),
                ),
                truth_requirements=(
                    "不得编造活动时间、地点、名额、权益、客户身份或到场承诺。",
                    "未提供权益时不得主动生成优惠、礼品或价格承诺。",
                    "默认按微信/私域/飞书触达话术输出，不默认生成邮件。",
                ),
                material_requirements=(
                    "至少需要活动名称、时间地点、邀约对象和邀约目标。",
                    "如涉及权益，需要提供权益内容、限制条件和有效期。",
                ),
                test_task_directions=("端午试驾活动客户邀约", "直播活动报名提醒"),
            ),
            Scenario(
                scenario_id="private_domain_campaign",
                name="私域活动转化话术",
                description="为社群、朋友圈、企微和私域运营生成分层触达与转化话术。",
                keywords=(
                    "私域活动",
                    "私域转化",
                    "社群活动",
                    "朋友圈",
                    "企微",
                    "微信群",
                    "群发",
                    "客户分层",
                    "转化话术",
                ),
                required_inputs=(
                    _input(
                        "audience_segment",
                        "人群分层",
                        "新客、老客、VIP、沉默客户或高意向客户。",
                        examples=("人群分层", "新客", "老客", "高意向客户"),
                    ),
                    _input(
                        "campaign_mechanism",
                        "活动机制",
                        "活动玩法、权益、参与条件或转化路径。",
                        examples=("活动机制", "参与条件", "转化路径"),
                    ),
                    _input(
                        "channel",
                        "私域渠道",
                        "朋友圈、微信群、企微私聊或飞书群。",
                        examples=("朋友圈", "微信群", "企微"),
                    ),
                    _input(
                        "conversion_goal",
                        "转化目标",
                        "报名、预约、复购、到店、领取资料或转介绍。",
                        examples=("报名", "预约", "复购", "到店"),
                    ),
                ),
                expected_outputs=(
                    _output("segment_strategy", "分层策略"),
                    _output("message_variants", "分层话术"),
                    _output("posting_sequence", "发布节奏"),
                    _output("image_prompt", "配图提示词", format_hint="可选"),
                    _output("review_checklist", "审查清单"),
                ),
                truth_requirements=(
                    "不得编造活动权益、价格、库存、客户数据或转化效果。",
                    "必须区分可确认事实和运营假设。",
                    "默认按微信/私域/飞书触达话术输出，不默认生成邮件。",
                ),
                material_requirements=(
                    "至少需要人群分层、活动机制、私域渠道和转化目标。",
                    "建议提供历史话术、素材链接、禁用词和活动规则。",
                ),
                test_task_directions=("私域活动转化话术", "朋友圈和社群分层话术"),
            ),
            Scenario(
                scenario_id="client_content_package",
                name="客户内容生产包",
                description="面向客户触达、邀约和私域转化生成文案、配图 brief 与视频脚本。",
                keywords=(
                    "客户邀约",
                    "客户触达",
                    "私域话术",
                    "客户文案",
                    "配图",
                    "生图",
                    "视频脚本",
                    "客户回访",
                    "活动邀约",
                ),
                required_inputs=(
                    _input("client_or_audience", "客户/受众", "客户类型、行业或人群。"),
                    _input(
                        "occasion", "触达场景", "邀约、回访、节日、活动或续约节点。"
                    ),
                    _input(
                        "brand_or_product",
                        "品牌/产品",
                        "涉及的品牌、车型、产品或服务。",
                    ),
                    _input(
                        "goal",
                        "业务目标",
                        examples=("邀约到店", "收集线索", "促进复购"),
                    ),
                    _input(
                        "offer",
                        "权益/活动信息",
                        "优惠、权益或活动机制。",
                        required=False,
                    ),
                    _input(
                        "channel",
                        "投放/发送渠道",
                        "飞书、微信、朋友圈、社群等。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output(
                        "message_draft",
                        "可发送文案",
                        format_hint="微信/私域/飞书短消息/社群话术",
                    ),
                    _output("subject_options", "标题备选", format_hint="3-5 条"),
                    _output(
                        "image_prompt",
                        "生图提示词",
                        format_hint="业务说明 + 模型 prompt",
                    ),
                    _output("video_script", "视频脚本", format_hint="镜头/旁白/字幕"),
                    _output("source_citations", "来源依据"),
                    _output("risk_notes", "风险提醒"),
                    _output("next_actions", "后续动作"),
                ),
                truth_requirements=(
                    "不得编造优惠、价格、客户身份、客户承诺或合作结果。",
                    "权益、活动机制和发送对象必须来自用户材料或知识库来源。",
                ),
                material_requirements=(
                    "至少需要客户/受众、触达场景、品牌/产品和业务目标。",
                    "如要输出生图/视频，需要提供或确认画面风格、平台和禁用元素。",
                ),
                test_task_directions=(
                    "客户邀约文案并配图",
                    "老客户回访话术加短视频脚本",
                ),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="brand_publicity",
        department_name="品宣部",
        aliases=("品宣部", "品宣", "品牌部", "宣发", "品牌宣传", "branding", "film"),
        functional_focus=("品牌表达", "海报文案", "社媒内容", "传播口径"),
        training_focus=("海报创意", "品牌调性", "社媒标题", "传播物料检查"),
        scenarios=(
            Scenario(
                scenario_id="poster_copy",
                name="海报/物料文案创意",
                description="围绕受众、卖点和调性生成多方向创意文案。",
                keywords=("海报", "物料", "文案创意", "slogan", "标题", "视觉文案"),
                required_inputs=(
                    _input("topic", "主题"),
                    _input("audience", "受众"),
                    _input("brand_tone", "品牌调性", required=False),
                    _input("selling_points", "核心卖点", required=False),
                ),
                expected_outputs=(
                    _output("creative_directions", "创意方向", format_hint="3 个方向"),
                    _output("copy_options", "文案备选"),
                    _output("visual_notes", "视觉建议"),
                    _output("compliance_notes", "注意事项"),
                ),
                truth_requirements=("不得虚构产品功效、奖项或品牌背书。",),
                material_requirements=(
                    "建议提供品牌口径、产品卖点、画面尺寸和禁用词。",
                ),
                test_task_directions=("端午海报文案创意", "活动主视觉标题备选"),
            ),
            Scenario(
                scenario_id="social_content",
                name="社媒传播内容",
                description="生成适合不同平台的传播标题、正文和互动设计。",
                keywords=("小红书", "抖音", "微博", "公众号", "社媒", "传播", "种草"),
                required_inputs=(
                    _input("platform", "发布平台"),
                    _input("topic", "内容主题"),
                    _input("audience", "目标受众", required=False),
                    _input("material", "素材信息", required=False),
                ),
                expected_outputs=(
                    _output("post_outline", "内容结构"),
                    _output("headline_options", "标题备选"),
                    _output("body_copy", "正文草稿"),
                    _output("interaction_hook", "互动引导"),
                ),
                truth_requirements=("热点和平台规则不确定时应标注需要复核。",),
                material_requirements=("如需跟热点，需要提供热点来源或允许实时查询。",),
                test_task_directions=("小红书种草笔记框架", "抖音短内容标题"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="planning",
        department_name="策划",
        aliases=("策划", "策划部", "策略部", "策略", "战略", "规划", "strategy"),
        functional_focus=("策略框架", "项目研判", "汇报结构", "洞察沉淀"),
        training_focus=("项目进度框架", "策略提案结构", "用户洞察", "竞品拆解"),
        scenarios=(
            Scenario(
                scenario_id="project_progress_framework",
                name="项目进度汇报框架",
                description="把项目现状整理成适合汇报的进度、风险和下一步。",
                keywords=(
                    "项目进度",
                    "跟进框架",
                    "进度汇报",
                    "项目跟进",
                    "周报",
                    "复盘",
                ),
                required_inputs=(
                    _input("project_name", "项目名称"),
                    _input("current_status", "当前状态"),
                    _input("milestones", "关键节点", required=False),
                    _input("blockers", "风险/阻塞", required=False),
                ),
                expected_outputs=(
                    _output("progress", "进度摘要"),
                    _output("risks", "风险判断"),
                    _output("decisions_needed", "待决策事项"),
                    _output("next_actions", "下一步动作"),
                ),
                truth_requirements=("项目进度、负责人和时间节点必须来自用户材料。",),
                material_requirements=(
                    "建议提供项目背景、当前进展、历史纪要或任务清单。",
                ),
                test_task_directions=("本周项目进度跟进框架", "项目复盘汇报结构"),
            ),
            Scenario(
                scenario_id="insight_brief",
                name="洞察/竞品简报",
                description="围绕问题拆出洞察、证据、机会点和行动建议。",
                keywords=("洞察", "竞品", "拆解", "分析", "策略", "机会点", "人群"),
                required_inputs=(
                    _input("question", "核心问题"),
                    _input("market_or_competitor", "市场/竞品对象", required=False),
                    _input("evidence", "已有材料", required=False),
                ),
                expected_outputs=(
                    _output("key_findings", "关键发现"),
                    _output("evidence_map", "证据链"),
                    _output("opportunities", "机会点"),
                    _output("recommendations", "建议动作"),
                ),
                truth_requirements=("没有证据时需要明确写出假设，不得伪造数据来源。",),
                material_requirements=(
                    "建议提供竞品链接、用户反馈、销售数据或调研摘要。",
                ),
                test_task_directions=("竞品活动拆解", "目标人群洞察框架"),
            ),
            Scenario(
                scenario_id="short_video_visual_brief",
                name="短视频脚本与生图 Brief",
                description="把策划任务拆成创意 brief、短视频脚本、分镜和生图 prompt。",
                keywords=(
                    "短视频脚本",
                    "视频脚本",
                    "分镜",
                    "生图",
                    "图片 prompt",
                    "视觉 brief",
                    "旁白",
                    "镜头",
                    "内容包",
                ),
                required_inputs=(
                    _input("project_or_brand", "项目/品牌", "项目、客户、品牌或车型。"),
                    _input(
                        "communication_goal",
                        "传播目标",
                        examples=("拉新", "种草", "活动预热"),
                    ),
                    _input("audience", "目标人群"),
                    _input(
                        "platform", "发布平台", examples=("抖音", "视频号", "小红书")
                    ),
                    _input(
                        "source_material",
                        "已有资料",
                        "历史方案、卖点、附件或知识库来源。",
                        required=False,
                    ),
                    _input(
                        "style_constraints",
                        "风格/禁用元素",
                        "画面风格、品牌口径、禁用词。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("creative_brief", "创意 Brief"),
                    _output("key_insight", "核心洞察"),
                    _output("video_script", "视频脚本"),
                    _output("storyboard", "分镜表"),
                    _output("voiceover", "旁白/字幕"),
                    _output("image_prompt", "生图提示词"),
                    _output("source_citations", "来源依据"),
                    _output("review_checklist", "审查清单"),
                ),
                truth_requirements=(
                    "必须区分资料事实与创意假设。",
                    "不得伪造客户、车型、卖点、数据或历史项目结论。",
                ),
                material_requirements=(
                    "建议提供历史方案、目标人群、平台、传播目标和品牌口径。",
                    "没有来源时必须先输出补资料请求，不进入深度生成。",
                ),
                test_task_directions=(
                    "做一个短视频脚本和生图 prompt",
                    "策划一个视频分镜内容包",
                ),
            ),
            Scenario(
                scenario_id="video_storyboard_production",
                name="短视频分镜生产",
                description="把策划 brief 拆成可拍摄的分镜、镜头调度、旁白字幕和素材清单。",
                keywords=(
                    "短视频分镜",
                    "视频分镜",
                    "分镜脚本",
                    "镜头脚本",
                    "拍摄脚本",
                    "镜头表",
                    "转场",
                    "旁白字幕",
                    "拍摄清单",
                ),
                required_inputs=(
                    _input(
                        "project_or_brand",
                        "项目/品牌",
                        "项目、客户、品牌、车型或活动。",
                        examples=("项目/品牌", "品牌", "车型", "活动"),
                    ),
                    _input(
                        "video_goal",
                        "视频目标",
                        "种草、预热、转化、招商、复盘或品牌传播。",
                        examples=("视频目标", "种草", "预热", "转化"),
                    ),
                    _input(
                        "audience",
                        "目标人群",
                        "目标客户、受众画像或渠道人群。",
                        examples=("目标人群", "受众", "客户画像"),
                    ),
                    _input(
                        "duration_platform",
                        "时长/平台",
                        "视频时长、发布平台和画幅。",
                        examples=("时长", "平台", "画幅", "抖音", "视频号"),
                    ),
                    _input(
                        "source_material",
                        "已有资料",
                        "产品卖点、活动机制、历史方案或附件。",
                        required=False,
                    ),
                ),
                expected_outputs=(
                    _output("creative_brief", "创意 Brief"),
                    _output(
                        "storyboard", "分镜表", format_hint="镜号/画面/镜头/字幕/旁白"
                    ),
                    _output("shot_list", "拍摄清单"),
                    _output("voiceover", "旁白/字幕"),
                    _output("editing_notes", "剪辑与转场建议"),
                    _output("review_checklist", "审查清单"),
                ),
                truth_requirements=(
                    "产品卖点、活动机制、客户信息和历史项目结论必须来自资料。",
                    "创意画面和镜头建议必须标注为创意假设，不得伪装成事实。",
                    "涉及品牌视觉、人物肖像、门店和车辆素材时必须列审查项。",
                ),
                material_requirements=(
                    "至少需要项目/品牌、视频目标、目标人群和时长/平台。",
                    "建议提供品牌口径、素材清单、禁用元素和历史方案。",
                ),
                test_task_directions=("短视频分镜脚本", "视频号拍摄镜头表"),
            ),
            Scenario(
                scenario_id="brand_review_check",
                name="品牌审查/合规检查",
                description="审查内容方案、文案、分镜或媒体 prompt 是否符合品牌口径和事实边界。",
                keywords=(
                    "品牌审查",
                    "品牌检查",
                    "合规审查",
                    "口径检查",
                    "禁用词",
                    "风险审查",
                    "传播审查",
                    "素材审查",
                    "prompt 审查",
                ),
                required_inputs=(
                    _input(
                        "review_material",
                        "待审材料",
                        "文案、分镜、prompt、海报稿、视频脚本或附件。",
                        examples=("待审材料", "文案", "分镜", "prompt", "附件"),
                    ),
                    _input(
                        "brand_guideline",
                        "品牌口径",
                        "品牌规范、项目口径、禁用词或审查标准。",
                        examples=("品牌口径", "品牌规范", "禁用词", "审查标准"),
                    ),
                    _input(
                        "usage_context",
                        "使用场景",
                        "发布平台、受众、活动场景或客户场景。",
                        examples=("使用场景", "发布平台", "受众", "活动场景"),
                    ),
                ),
                expected_outputs=(
                    _output("risk_summary", "风险摘要"),
                    _output("fact_check_items", "事实核查项"),
                    _output("brand_consistency_notes", "品牌一致性意见"),
                    _output("revision_suggestions", "修改建议"),
                    _output("approval_checklist", "确认清单"),
                ),
                truth_requirements=(
                    "不得把未提供的品牌规范、法务要求或客户承诺当作事实。",
                    "必须区分确定违规、疑似风险和需要人工确认的项目。",
                    "没有品牌口径或待审材料时必须先补资料，不得直接给通过结论。",
                ),
                material_requirements=(
                    "至少需要待审材料、品牌口径和使用场景。",
                    "建议提供历史通过案例、禁用词表、平台规则和法务要求。",
                ),
                test_task_directions=("品牌审查和禁用词检查", "视频脚本口径检查"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="executive_office",
        department_name="总经办",
        aliases=("总经办", "办公室", "总办", "行政办", "总经理办公室"),
        functional_focus=("会议纪要", "决策跟进", "制度通知", "跨部门协调"),
        training_focus=("正式纪要", "决策事项追踪", "通知公告", "老板视角摘要"),
        scenarios=(
            Scenario(
                scenario_id="meeting_minutes",
                name="会议纪要整理",
                description="把会议讨论整理为正式纪要、决策和待办。",
                keywords=(
                    "会议纪要",
                    "会议要点",
                    "正式纪要",
                    "会议整理",
                    "决议",
                    "纪要",
                ),
                required_inputs=(
                    _input("meeting_topic", "会议主题"),
                    _input("raw_notes", "原始记录"),
                    _input("attendees", "参会人", required=False),
                ),
                expected_outputs=(
                    _output("summary", "会议摘要"),
                    _output("decisions", "决策事项"),
                    _output("action_items", "行动项"),
                    _output("open_questions", "遗留问题"),
                ),
                truth_requirements=(
                    "不得新增会议中未出现的决策、人员承诺或截止时间。",
                ),
                material_requirements=(
                    "建议提供聊天记录、录音转写、参会人和会议背景。",
                ),
                test_task_directions=("昨天会议要点正式纪要", "老板会议决策追踪表"),
            ),
            Scenario(
                scenario_id="announcement_notice",
                name="通知/公告起草",
                description="生成正式、清晰、低歧义的内部通知。",
                keywords=("通知", "公告", "制度", "安排", "发文", "内部信"),
                required_inputs=(
                    _input("topic", "通知主题"),
                    _input("audience", "通知对象"),
                    _input("policy_or_action", "要求/安排"),
                    _input("deadline", "时间要求", required=False),
                ),
                expected_outputs=(
                    _output("notice_draft", "通知正文"),
                    _output("key_points", "要点清单"),
                    _output("faq", "可能追问", format_hint="可选"),
                ),
                truth_requirements=("涉及制度、奖惩和人事安排必须以原文材料为准。",),
                material_requirements=(
                    "建议提供制度依据、执行范围、发布时间和联系人。",
                ),
                test_task_directions=("内部活动通知", "制度调整公告草稿"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="execution_ops",
        department_name="执行运营",
        aliases=("执行运营", "运营", "执行", "项目执行", "运营部", "operations"),
        functional_focus=("任务拆解", "排期推进", "现场执行", "风险闭环"),
        training_focus=("执行步骤", "时间节点", "负责人拆分", "风险预案"),
        scenarios=(
            Scenario(
                scenario_id="execution_plan",
                name="执行排期拆解",
                description="把活动或项目拆成可执行步骤、负责人和时间节点。",
                keywords=("拆解", "执行步骤", "时间节点", "排期", "执行计划", "落地"),
                required_inputs=(
                    _input("project_or_event", "项目/活动"),
                    _input("deadline", "最终时间"),
                    _input("owners", "参与角色", required=False),
                    _input("constraints", "限制条件", required=False),
                ),
                expected_outputs=(
                    _output("work_breakdown", "任务拆解"),
                    _output("timeline", "时间排期"),
                    _output("owner_matrix", "负责人矩阵"),
                    _output("risk_controls", "风险预案"),
                ),
                truth_requirements=(
                    "负责人、场地、预算和截止时间不明确时需要标注待确认。",
                ),
                material_requirements=(
                    "建议提供活动 brief、人员分工、硬截止时间和交付物清单。",
                ),
                test_task_directions=("端午营销活动执行步骤", "线下活动排期与风险表"),
            ),
            Scenario(
                scenario_id="task_checklist",
                name="待办检查清单",
                description="把模糊任务转成检查清单和验收标准。",
                keywords=("待办", "清单", "检查表", "验收", "SOP", "流程"),
                required_inputs=(
                    _input("task_goal", "任务目标"),
                    _input("deliverables", "交付物", required=False),
                    _input("quality_bar", "验收标准", required=False),
                ),
                expected_outputs=(
                    _output("checklist", "检查清单"),
                    _output("acceptance_criteria", "验收标准"),
                    _output("handoff_notes", "交接说明"),
                ),
                truth_requirements=("验收标准不明确时应给出待确认字段。",),
                material_requirements=("建议提供历史 SOP、客户要求或交付模板。",),
                test_task_directions=("活动执行检查清单", "项目交接 SOP"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="general_affairs",
        department_name="综合部",
        aliases=("综合部", "综合", "行政", "行政综合", "办公室综合"),
        functional_focus=("行政通知", "内部协调", "资料归档", "服务答疑"),
        training_focus=("通知整理", "跨部门事项", "归档规范", "标准回复"),
        scenarios=(
            Scenario(
                scenario_id="admin_notice",
                name="行政通知/制度说明",
                description="把行政安排或内部规则整理为清晰通知、执行要点和 FAQ。",
                keywords=(
                    "行政通知",
                    "办公规则",
                    "制度说明",
                    "内部通知",
                    "领用",
                    "行政",
                ),
                required_inputs=(
                    _input("policy_or_arrangement", "制度/安排原文"),
                    _input("audience", "适用对象"),
                    _input("effective_time", "执行时间", required=False),
                    _input("contact", "联系人", required=False),
                ),
                expected_outputs=(
                    _output("notice_draft", "通知正文"),
                    _output("key_points", "执行要点"),
                    _output("faq", "常见问题"),
                    _output("open_questions", "待确认项"),
                ),
                truth_requirements=(
                    "制度条款、适用范围和执行时间必须来自用户提供材料。",
                ),
                material_requirements=(
                    "建议提供制度原文、适用范围、执行时间和联系人。",
                ),
                test_task_directions=("办公用品领用规则通知", "内部流程调整说明"),
            ),
            Scenario(
                scenario_id="coordination_digest",
                name="跨部门协调清单",
                description="把多方反馈整理为待办、负责人、截止时间和风险。",
                keywords=("跨部门", "协调", "反馈汇总", "待办", "负责人", "行政协调"),
                required_inputs=(
                    _input("coordination_topic", "协调事项"),
                    _input("raw_feedback", "各方反馈"),
                    _input("deadline", "截止时间", required=False),
                    _input("participants", "参与部门/人员", required=False),
                ),
                expected_outputs=(
                    _output("summary", "反馈摘要"),
                    _output("action_items", "待办清单"),
                    _output("owner_matrix", "负责人矩阵"),
                    _output("risks", "风险与待确认项"),
                ),
                truth_requirements=("不得新增未被确认的负责人、承诺或截止时间。",),
                material_requirements=(
                    "建议提供聊天记录、表单反馈、参与人员和目标时间。",
                ),
                test_task_directions=("团建安排反馈汇总", "跨部门事项推进表"),
            ),
        ),
    ),
    DepartmentWorkflow(
        department_id="finance",
        department_name="财务部",
        aliases=("财务", "财务部", "会计", "出纳", "财务管理"),
        functional_focus=("报销审核", "发票检查", "预算汇总", "费用分析"),
        training_focus=("报销材料检查", "发票缺项提醒", "费用分类", "预算执行汇总"),
        scenarios=(
            Scenario(
                scenario_id="reimbursement_invoice_check",
                name="报销/发票材料检查",
                description="把报销说明、票据信息和附件整理为缺项清单与复核提醒。",
                keywords=("报销", "发票", "票据", "付款", "附件", "缺项", "财务审核"),
                required_inputs=(
                    _input("expense_context", "费用事项", "报销或付款对应的业务事项。"),
                    _input(
                        "invoice_info",
                        "发票/票据信息",
                        "发票内容、金额、税号或附件摘要。",
                    ),
                    _input(
                        "policy_basis",
                        "制度依据",
                        "对应报销制度或审批要求。",
                        required=False,
                    ),
                    _input("approver", "审批人/部门", required=False),
                ),
                expected_outputs=(
                    _output("material_checklist", "材料检查清单"),
                    _output("missing_items", "缺失/待补充项"),
                    _output("risk_flags", "复核风险提示"),
                    _output("next_actions", "下一步处理建议"),
                ),
                truth_requirements=(
                    "金额、发票真伪、付款对象和审批结论必须由财务人员基于原始凭证确认。",
                ),
                material_requirements=(
                    "建议提供发票截图、报销说明、合同/订单、付款申请和公司制度依据。",
                ),
                test_task_directions=("报销发票材料检查清单", "付款申请缺项提醒"),
            ),
            Scenario(
                scenario_id="budget_cost_summary",
                name="预算/费用汇总",
                description="把费用明细整理为分类汇总、异常项和待确认问题。",
                keywords=("预算", "费用", "成本", "支出", "汇总", "对账", "预算执行"),
                required_inputs=(
                    _input("period", "统计周期"),
                    _input("expense_items", "费用明细"),
                    _input("budget_baseline", "预算口径", required=False),
                    _input("category_rules", "分类规则", required=False),
                ),
                expected_outputs=(
                    _output("cost_summary", "费用分类汇总"),
                    _output("variance_notes", "预算差异说明"),
                    _output("exceptions", "异常/待确认项"),
                    _output("report_draft", "汇报口径草稿"),
                ),
                truth_requirements=(
                    "费用数字必须来自用户提供明细，不得自行补数或替代财务核算。",
                ),
                material_requirements=(
                    "建议提供费用明细表、预算口径、科目分类规则和历史对账记录。",
                ),
                test_task_directions=("月度费用分类汇总", "项目预算执行差异说明"),
            ),
        ),
    ),
)
