"""Post-process dianchi_tech reports with machine facts.

The narrative report is generated by agy, but pipeline facts are deterministic:
raw_news.md tells which search channel was used, searcher_meta.json records the
actual channel, and run.json records exit codes/durations. This guard rewrites
the report header and inserts a small fact line so those facts cannot drift.
"""

from __future__ import annotations

import argparse
import json
import shutil
from datetime import date as _date
from pathlib import Path
from typing import Any

DATA_ROOT = Path("/Users/dianchi/DC-Agent/data/dianchi_tech")
DESKTOP_REPORT_DIR = Path.home() / "Desktop" / "日常任务报告"
NAS_REPORT_DIR = Path("/Users/dianchi/nas_kb/inbox/日常任务报告")


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return {}


def _raw_source_line(day_dir: Path) -> str:
    raw_path = day_dir / "raw_news.md"
    if not raw_path.exists():
        return "> 数据源：UNKNOWN（raw_news.md 缺失）"
    for line in raw_path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.strip():
            return line.strip()
    return "> 数据源：UNKNOWN（raw_news.md 为空）"


def _expected_report_header(raw_source_line: str) -> str:
    source = raw_source_line.strip()
    if source.startswith(">"):
        source = source[1:].strip()
    return f"> 给产品 owner 蔡挺 · {source} + agy CLI / Antigravity（分析/学习/巡检）"


def _channel_label(meta: dict[str, Any]) -> str:
    channel = str(meta.get("channel") or "unknown")
    agy = meta.get("agy") or {}
    if channel == "agy":
        return f"agy/{agy.get('kind', 'unknown')}"
    if channel == "gemini_grounding_fallback":
        return f"aihubmix grounding fallback（agy {agy.get('kind', 'unknown')}）"
    if channel == "openai_compat_2nd_fallback":
        return f"aihubmix OpenAI fallback（agy {agy.get('kind', 'unknown')}）"
    return channel


def _fact_line(
    run_meta: dict[str, Any], searcher_meta: dict[str, Any], report_path: Path
) -> str:
    agy = run_meta.get("agy") or {}
    analysis = run_meta.get("analysis") or run_meta.get("claude") or {}
    provider = analysis.get("provider") or ("claude" if "claude" in run_meta else "agy")
    report_bytes = report_path.stat().st_size if report_path.exists() else 0
    return (
        "> 运行事实："
        f"阶段 A={_channel_label(searcher_meta)}，exit={agy.get('exit', '?')}，{agy.get('duration_seconds', '?')}s；"
        f"阶段 B={provider} exit={analysis.get('exit', '?')}，{analysis.get('duration_seconds', '?')}s；"
        f"report={report_bytes} bytes"
    )


def _correction_note(searcher_meta: dict[str, Any]) -> str:
    if searcher_meta.get("channel") == "agy":
        return (
            "> 校正说明：本报告以 raw_news.md / searcher_meta.json / run.json 为准；"
            "5/28 阶段 A 实际为 agy 主通道成功，不是 aihubmix 降级。"
        )
    return (
        "> 校正说明：本报告以 raw_news.md / searcher_meta.json / run.json 为准；"
        "若正文叙述与本行冲突，以机器事实为准。"
    )


def _ensure_header(lines: list[str], expected_header: str) -> tuple[int, bool]:
    for index, line in enumerate(lines[:12]):
        if line.startswith("> 给产品 owner 蔡挺 ·"):
            if line != expected_header:
                lines[index] = expected_header
                return index, True
            return index, False
    insert_at = 1 if lines and lines[0].startswith("# ") else 0
    lines.insert(insert_at, "")
    lines.insert(insert_at + 1, expected_header)
    return insert_at + 1, True


def _insert_after(lines: list[str], index: int, line: str) -> bool:
    if line in lines[:12]:
        return False
    insert_at = min(index + 1, len(lines))
    lines.insert(insert_at, line)
    return True


def _remove_stale_fact_lines(lines: list[str]) -> bool:
    changed = False
    kept: list[str] = []
    for line in lines:
        if line.startswith("> 运行事实："):
            changed = True
            continue
        kept.append(line)
    if changed:
        lines[:] = kept
    return changed


def _remove_stale_correction_notes(lines: list[str]) -> bool:
    changed = False
    kept: list[str] = []
    for line in lines:
        if line.startswith("> 校正说明："):
            changed = True
            continue
        kept.append(line)
    if changed:
        lines[:] = kept
    return changed


def _ensure_single_prefixed_line(
    lines: list[str],
    prefix: str,
    line: str,
    insert_after_index: int,
) -> tuple[int, bool]:
    changed = False
    found_index: int | None = None
    kept: list[str] = []
    for old_line in lines:
        if old_line.startswith(prefix):
            if found_index is None:
                found_index = len(kept)
                kept.append(line)
                changed = changed or old_line != line
            else:
                changed = True
        else:
            kept.append(old_line)
    if found_index is not None:
        if changed:
            lines[:] = kept
        return found_index, changed

    insert_at = min(insert_after_index + 1, len(lines))
    lines.insert(insert_at, line)
    return insert_at, True


def _patch_known_contradictions(
    text: str, searcher_meta: dict[str, Any]
) -> tuple[str, list[str]]:
    corrections: list[str] = []
    if searcher_meta.get("channel") == "agy":
        replacements = {
            "searcher.py 走 aihubmix + google_search grounding": "searcher.py 走 agy CLI / Antigravity 主通道",
            "gemini 主通道一把过": "agy 主通道一把过",
            "aihubmix gemini-3.5-flash + google_search grounding（搜索/整理）": "agy CLI / Antigravity（主通道）",
        }
        for old, new in replacements.items():
            if old in text:
                text = text.replace(old, new)
                corrections.append(f"replace: {old} -> {new}")
    return text, corrections


def _find_header_index(lines: list[str]) -> int:
    return next(
        (
            index
            for index, line in enumerate(lines[:12])
            if line.startswith("> 给产品 owner 蔡挺 ·")
        ),
        1 if lines and lines[0].startswith("# ") else 0,
    )


def _refresh_fact_line(
    report_path: Path,
    run_meta: dict[str, Any],
    searcher_meta: dict[str, Any],
) -> bool:
    for _ in range(3):
        text = report_path.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        _remove_stale_fact_lines(lines)
        header_index = _find_header_index(lines)
        fact = _fact_line(run_meta, searcher_meta, report_path)
        _insert_after(lines, header_index, fact)
        refreshed = "\n".join(lines).rstrip() + "\n"
        if refreshed == text:
            return False
        report_path.write_text(refreshed, encoding="utf-8")
    return True


def _sync_copy(report_path: Path, date_str: str, target_dir: Path) -> dict[str, Any]:
    if target_dir == NAS_REPORT_DIR and not Path("/Users/dianchi/nas_kb").is_dir():
        return {"success": False, "skipped": True, "reason": "NAS 未挂载"}
    try:
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / f"巅池-技术日报-{date_str}.md"
        shutil.copyfile(report_path, target)
        return {
            "success": True,
            "path": str(target),
            "bytes": target.stat().st_size,
        }
    except OSError as exc:
        return {"success": False, "error": f"{type(exc).__name__}: {exc}"}


def guard_report(
    day_dir: Path,
    date_str: str | None = None,
    *,
    sync_copies: bool = False,
) -> dict[str, Any]:
    report_path = day_dir / "report.md"
    if not report_path.exists() or report_path.stat().st_size == 0:
        return {"ok": False, "changed": False, "error": "report.md missing or empty"}

    raw_source = _raw_source_line(day_dir)
    expected_header = _expected_report_header(raw_source)
    run_path = day_dir / "run.json"
    run_meta = _read_json(run_path)
    searcher_meta = _read_json(day_dir / "searcher_meta.json")

    text = report_path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    changed = False
    corrections: list[str] = []

    header_index, header_changed = _ensure_header(lines, expected_header)
    if header_changed:
        changed = True
        corrections.append("ensure source header")

    header_index = _find_header_index(lines)
    fact = _fact_line(run_meta, searcher_meta, report_path)
    fact_index, fact_changed = _ensure_single_prefixed_line(
        lines, "> 运行事实：", fact, header_index
    )
    changed = fact_changed or changed
    note = _correction_note(searcher_meta)
    _, note_changed = _ensure_single_prefixed_line(
        lines, "> 校正说明：", note, fact_index
    )
    changed = note_changed or changed

    new_text = "\n".join(lines).rstrip() + "\n"
    new_text, contradiction_corrections = _patch_known_contradictions(
        new_text, searcher_meta
    )
    if contradiction_corrections:
        changed = True
        corrections.extend(contradiction_corrections)

    if changed:
        report_path.write_text(new_text, encoding="utf-8")
        if _refresh_fact_line(report_path, run_meta, searcher_meta):
            corrections.append("refresh fact line bytes")
        if run_meta:
            run_meta["report_bytes"] = report_path.stat().st_size
            run_path.write_text(
                json.dumps(run_meta, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )

    copy_results: dict[str, Any] = {}
    if sync_copies:
        date_for_copy = date_str or day_dir.name
        copy_results = {
            "desktop": _sync_copy(report_path, date_for_copy, DESKTOP_REPORT_DIR),
            "nas": _sync_copy(report_path, date_for_copy, NAS_REPORT_DIR),
        }

    result = {
        "ok": True,
        "changed": changed,
        "date": date_str or day_dir.name,
        "raw_source": raw_source,
        "expected_header": expected_header,
        "searcher_channel": searcher_meta.get("channel"),
        "corrections": corrections,
        "copies": copy_results,
    }
    (day_dir / "report_guard.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", default=_date.today().isoformat())
    parser.add_argument("--day-dir", default="")
    parser.add_argument("--sync-copies", action="store_true")
    args = parser.parse_args()
    day_dir = Path(args.day_dir) if args.day_dir else DATA_ROOT / args.date
    result = guard_report(day_dir, args.date, sync_copies=args.sync_copies)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(main())
